dbipsum.vocab = {
	phrase : [
		"is going to need to surface that",
		"would benefit from a deep-dive",
		"let's capture that",
		"don't slouch darling",
		"let's use gamification to leverage the new millenium usage drivers",
		"damn these electric pants",
		"Yay! Business!",
		"delicate sensibilities",
		"angry milk will countermand my trousers",
		"is political correctness gone mad",
		"and fiercly proud of it",
		"Now, you hold on a minute, sugar-tits!"
	],
	verb : [
		"gamify",
		"gamificate",
		"facilitate",
		"verbify",
		"verbificate",
		"facilate",
		"follow",
		"doubebaggify",
		"cache",
		"drown",
		"obfuscate"
	],
	noun : [
		"douchebag",
		"douche",
		"hipster",
		"mobile device",
		"manifest",
		"cache",
		"fixie",
		"herbal infusion",
		"cleansing milk preparation",
		"olives",
		"ironic facial hair",
		"my razor sharp parting",
		"stout and sensible shoes",
		"enteprise architecture"
	],
	padding : [
		"lorem",
		"ipsum",
		"rhubarb",
		"pantomime",
		"thingamibob",
		"within",
		"without",
		"preponderonce",
		"and",
		"or",
		"should",
		"never",
		"might",
		"was",
		"where",
		"is",
		"did"
	]
};