dbipsum.vocab = {
	phrase : [
		"is going to need to surface that",
		"would benefit from a deep-dive",
		"let's capture that",
		"don't slouch darling",
		"let's use gamification to leverage the new millenium usage drivers",
		"damn these electric pants",
		"delicate sensibilities",
		"angry milk will countermand my trousers",
		"is political correctness gone mad",
		"and fiercly proud of it",
		"now, you hold on a minute, sugar-tits",
		"bring me solutions, don't bring me problems",
		"accelearte the ideation process",
		"your mailbox quota has been exceeded",
		"leverage social media",
		"capture the market share using app stores",
		"time is money",
		"that's bang out of order",
		"is an expensive meeting",
		"provides expert though leadership",
		"I know, I know, I know, I know, I know",
		"you are getting confused"
	],
	verb : [
		"gamify",
		"gamificate",
		"facilitate",
		"verbify",
		"verbificate",
		"facilate",
		"follow",
		"douchebaggify",
		"cache",
		"drown",
		"obfuscate",
		"synergize",
		"ideate",
		"leverage",
		"nextcast",
		"intelligize"
	],
	noun : [
		"douchebag",
		"douche",
		"hipster",
		"mobile device",
		"manifest",
		"cache",
		"fixie",
		"herbal infusion",
		"cleansing milk preparation",
		"olives",
		"ironic facial hair",
		"my razor sharp parting",
		"stout and sensible shoes",
		"enterprise architecture",
		"ball bag",
		"solutioneer",
		"focus group"
	],
	padding : [
		"lorem",
		"ipsum",
		"rhubarb",
		"pantomime",
		"thingamibob",
		"within",
		"without",
		"preponderonce",
		"and",
		"or",
		"should",
		"never",
		"might",
		"was",
		"where",
		"is",
		"did",
		"the",
		"this",
		"that",
		"they",
		"our",
		"nextification",
		"nextcasting"
	]
};